export function isCyberDomain(question: string) {
  const allowed = [
    "cyber",
    "security",
    "scan",
    "osint",
    "malware",
    "phishing",
    "dns",
    "whois",
    "dark web",
    "steganography",
    "privacy",
    "breach",
    "threat",
    "vulnerability",
    "data safe",
    "defense",
    "firewall",
    "antivirus",
    "ransomware",
    "spyware",
    "adware",
    "trojan",
    "worm",
    "botnet",
    "ddos",
    "cyberscan ai",
    "cyberscan",
    "ethical hacking",
    "penetration testing",
    "infosec",
    "cyber awareness",
    "cyber hygiene",
    "cyber threat intelligence",  
    "AI",
    "artificial intelligence",
    "machine learning",
    "deep learning",
    "neural network",
    "automation",
    "data analysis",
    "GameZone",
  ]

  const q = question.toLowerCase()
  return allowed.some((k) => q.includes(k))
}
